name: petmarket_bo_app
description: Esta es la app para la compañia de Pet Market Bolivia.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.3
  cloud_firestore: ^4.3.0
  equatable: ^2.0.5
  validators: ^3.0.0
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.2.1
  google_fonts: ^4.0.3
  file_picker: ^5.2.5
  hydrated_bloc: ^9.0.0
  path_provider: ^2.0.12
  badges: ^3.0.2
  url_launcher: ^6.1.9
  flutter_native_splash: ^2.2.18
  flutter_launcher_icons: ^0.12.0
  favorite_button: ^0.0.4
  envied: ^0.3.0
  http: ^0.13.5
  intl: ^0.18.1

flutter_native_splash:
  color: "#428bca"
  image: assets/images/petmarket_logo.png
  android: true
  ios: true
  web: false
  fill: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0
  build_runner: ^2.3.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/1024.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/1024.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf
    - family: Lemon Days
      fonts:
        - asset: assets/fonts/Lemon Days.ttf
    - family: Marhey
      fonts:
        - asset: assets/fonts/Marhey.ttf
    - family: Renogare
      fonts:
        - asset: assets/fonts/Renogare-Regular.otf
    - family: MontBlanc
      fonts:
        - asset: assets/fonts/MontBlanc-Trial-Regular.otf 
        - asset: assets/fonts/MontBlanc-Trial-SemiBold.otf
          weight: 600
        - asset: assets/fonts/MontBlanc-Trial-Light.otf
          weight: 300
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
        - asset: assets/fonts/Inter-Light.otf
          weight: 300
        - asset: assets/fonts/Inter-Bold.otf
          weight: 600
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
