// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOvfJZymsTYkSpSTqjVr0OUc0iZro9GAo',
    appId: '1:196504032011:web:7a67371b0d6f0f83f2080e',
    messagingSenderId: '196504032011',
    projectId: 'petmarket-bo-app',
    authDomain: 'petmarket-bo-app.firebaseapp.com',
    storageBucket: 'petmarket-bo-app.appspot.com',
    measurementId: 'G-HJ1XEWVKKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_jywecTfwksAwvqvVIUpAvS2NhoFukzE',
    appId: '1:196504032011:android:e8068f7d2f8985edf2080e',
    messagingSenderId: '196504032011',
    projectId: 'petmarket-bo-app',
    storageBucket: 'petmarket-bo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQe1HU6kctJLDR5h25SGQd9wIjKinF11M',
    appId: '1:196504032011:ios:0192d6757796aa44f2080e',
    messagingSenderId: '196504032011',
    projectId: 'petmarket-bo-app',
    storageBucket: 'petmarket-bo-app.appspot.com',
    iosClientId: '196504032011-i048go2ctuuhnh0kk49igs308kji4ihe.apps.googleusercontent.com',
    iosBundleId: 'com.example.petmarketBoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQe1HU6kctJLDR5h25SGQd9wIjKinF11M',
    appId: '1:196504032011:ios:0192d6757796aa44f2080e',
    messagingSenderId: '196504032011',
    projectId: 'petmarket-bo-app',
    storageBucket: 'petmarket-bo-app.appspot.com',
    iosClientId: '196504032011-i048go2ctuuhnh0kk49igs308kji4ihe.apps.googleusercontent.com',
    iosBundleId: 'com.example.petmarketBoApp',
  );
}
